/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as OrderIndexRouteImport } from './routes/order/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CatalogProductIdRouteImport } from './routes/catalog/$productId'
import { Route as AdminProductIndexRouteImport } from './routes/admin/product/index'
import { Route as AdminOrderIndexRouteImport } from './routes/admin/order/index'
import { Route as AdminCustomerIndexRouteImport } from './routes/admin/customer/index'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIndexRoute = OrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CatalogProductIdRoute = CatalogProductIdRouteImport.update({
  id: '/catalog/$productId',
  path: '/catalog/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductIndexRoute = AdminProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrderIndexRoute = AdminOrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomerIndexRoute = AdminCustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalog/$productId': typeof CatalogProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cart': typeof CartIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/order': typeof OrderIndexRoute
  '/register': typeof RegisterIndexRoute
  '/admin/customer': typeof AdminCustomerIndexRoute
  '/admin/order': typeof AdminOrderIndexRoute
  '/admin/product': typeof AdminProductIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog/$productId': typeof CatalogProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/cart': typeof CartIndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/order': typeof OrderIndexRoute
  '/register': typeof RegisterIndexRoute
  '/admin/customer': typeof AdminCustomerIndexRoute
  '/admin/order': typeof AdminOrderIndexRoute
  '/admin/product': typeof AdminProductIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalog/$productId': typeof CatalogProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/cart/': typeof CartIndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/order/': typeof OrderIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/admin/customer/': typeof AdminCustomerIndexRoute
  '/admin/order/': typeof AdminOrderIndexRoute
  '/admin/product/': typeof AdminProductIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalog/$productId'
    | '/admin/'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/login'
    | '/order'
    | '/register'
    | '/admin/customer'
    | '/admin/order'
    | '/admin/product'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog/$productId'
    | '/admin'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/login'
    | '/order'
    | '/register'
    | '/admin/customer'
    | '/admin/order'
    | '/admin/product'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalog/$productId'
    | '/admin/'
    | '/cart/'
    | '/catalog/'
    | '/checkout/'
    | '/login/'
    | '/order/'
    | '/register/'
    | '/admin/customer/'
    | '/admin/order/'
    | '/admin/product/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatalogProductIdRoute: typeof CatalogProductIdRoute
  CartIndexRoute: typeof CartIndexRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  OrderIndexRoute: typeof OrderIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/': {
      id: '/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/catalog/$productId': {
      id: '/catalog/$productId'
      path: '/catalog/$productId'
      fullPath: '/catalog/$productId'
      preLoaderRoute: typeof CatalogProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/product/': {
      id: '/admin/product/'
      path: '/product'
      fullPath: '/admin/product'
      preLoaderRoute: typeof AdminProductIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/order/': {
      id: '/admin/order/'
      path: '/order'
      fullPath: '/admin/order'
      preLoaderRoute: typeof AdminOrderIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customer/': {
      id: '/admin/customer/'
      path: '/customer'
      fullPath: '/admin/customer'
      preLoaderRoute: typeof AdminCustomerIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomerIndexRoute: typeof AdminCustomerIndexRoute
  AdminOrderIndexRoute: typeof AdminOrderIndexRoute
  AdminProductIndexRoute: typeof AdminProductIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomerIndexRoute: AdminCustomerIndexRoute,
  AdminOrderIndexRoute: AdminOrderIndexRoute,
  AdminProductIndexRoute: AdminProductIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CatalogProductIdRoute: CatalogProductIdRoute,
  CartIndexRoute: CartIndexRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  OrderIndexRoute: OrderIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
